local run_i = function()
	vim.cmd("w")
	local path = vim.fn.expand("%:p:h")
	local name = vim.fn.expand("%:p")
	local buf = vim.fn.bufnr()
	vim.cmd("belowright sp")
	vim.cmd("enew")
	vim.cmd("set filetype=terminal")
	vim.cmd("lcd "..path)
	vim.fn.termopen({ "python", "-i", name })
end
local run = function()
	vim.cmd("w")
	local path = vim.fn.expand("%:p:h")
	local name = vim.fn.expand("%:p")
	local buf = vim.fn.bufnr()
	vim.cmd("belowright sp")
	vim.cmd("enew")
	vim.cmd("set filetype=terminal")
	vim.cmd("lcd "..path)
	vim.fn.termopen({ "python", name })
end

vim.keymap.set("n", "<F5>", run, { buffer = 0, desc = "Run File" })
vim.keymap.set("n", "<F6>", run_i, { buffer = 0, desc = "Test File" })
